### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by npoltorapavlo** [rdkcentral/rdkservices#2284]
I think the versioning provided by Thunder:

https://github.com/rdkcentral/Thunder/blob/master/Source/plugins/JSONRPC.h#L116

is for the [rare] case when multiple variants of the same API should **coexist**. API version (uint8_t: 1, 2, etc) is not the same as the plugin version used for the documentation:

https://github.com/rdkcentral/rdkservices/blob/sprint/2201/FrameRate/FrameRatePlugin.json#L9

(In a similar fashion, when using SQLite library, version "3.38.0" is specified in the library documentation or changelog, but it's not specified when calling "sqlite3_open". If the library has multiple variants of the same API, it can be "sqlite3_open" or "sqlite3_open_v2" with additional parameters. "sqlite3_open_v2" doesn't mean it was added in SQLite "3.2.0", it means there are 2 variants to call this API)

I would expect the same logic in rdkservices but it's different:

For example, "org.rdk.FrameRate.**2**.setDisplayFrameRate" doesn't mean it differs from "org.rdk.FrameRate.**1**.setDisplayFrameRate". Instead, "org.rdk.FrameRate.**1**.setDisplayFrameRate" doesn't exist. On the other hand, "org.rdk.FrameRate.**1**.updateFps" and "org.rdk.FrameRate.**2**.updateFps" are the same. This looks like **"2" = plugin version**.

But in Thunder **"2"** is part of the method and not the callsign:

https://github.com/rdkcentral/Thunder/blob/master/Source/core/JSONRPC.h#L154

(This makes sense as no version is needed to activate the plugin)

However, the logic in AbstractPlugin:

https://github.com/rdkcentral/rdkservices/blob/sprint/2201/helpers/AbstractPlugin.h

makes it look like **"2" = plugin version**. This is confusing, because for the user, like an app, there's no difference. When app calls "org.rdk.FrameRate.**1**.setDisplayFrameRate" or "org.rdk.FrameRate.**2**.setDisplayFrameRate" and the plugin doesn't have it, the result in both cases will be an error (-32601 "Unknown method." or -32602 "Requested version is not supported."). There's no need for the app to specify that "setDisplayFrameRate" was added in "version 2", or "version 38" in order to just call it.

(As if SQLite adds a new API in version "3.38.1" and calls it "sqlite3_reopen_v3_38_1". At the same time, adds "sqlite3_open_v3_38_1" which doesn't differ from "sqlite3_open" and both can be called. Not sure if this makes sense, but such is the logic in AbstractPlugin)

Suggesting to remove AbstractPlugin and the logic it introduces.

**Comment by anand-ky** [comment]
to be handled in https://ccp.sys.comcast.net/browse/RDK-35564
