### ISSUE TITLE
Github workflow for unit tests

### ISSUE THREAD

**Issue by npoltorapavlo** [rdkcentral/rdkservices#2419]
Unit testing (https://github.com/rdkcentral/rdkservices/tree/sprint/2203/RdkServicesTest) is manually triggered. Should automate it to track: the unit tests are building, passing, Valgrind reports no new findings. Indicate coverage in some way.

**Comment by anand-ky** [comment]
Pls look at triggering unit tests as part of Pull Request checks.

**Comment by npoltorapavlo** [comment]
#2428 and #2436
