### ISSUE TITLE
servicemanager legacy code

### ISSUE THREAD

**Issue by npoltorapavlo** [rdkcentral/rdkservices#2847]
"success" param in the api result is the legacy code.

In Thunder JSON-RPC there are error codes. If ERROR_NONE the message sends a "result" object. Otherwise the message sends an error code. Error codes are part of the interface: https://github.com/rdkcentral/rdkservices/blob/df8b598e1943e0f35d7af8cf77943e034b278a1d/Messenger/Messenger.json#L76-L77

A caller shouldn't have to inspect "result" object to see if the api succeeded or not.

"getMeSomeData" methods are also the legacy code.

In Thunder JSON-RPC there are properties / readonly properties: https://github.com/rdkcentral/rdkservices/blob/df8b598e1943e0f35d7af8cf77943e034b278a1d/LocationSync/LocationSyncJsonRpc.cpp#L36

**Comment by anand-ky** [comment]
"success" parameter was added for legacy reasons to support comcast ServiceManager APIs. But going forward, newer APIs should return only error object to match the spec. Also existing APIs should return error object along with success:false in the response.

**Comment by npoltorapavlo** [comment]
management preferred to stay with xre ServiceManager style so closing
