### ISSUE TITLE
Plugins should stop threads in Deinitialize

### ISSUE THREAD

**Issue by npoltorapavlo** [rdkcentral/rdkservices#3445]
`std::thread` should be joined by a plugin before the destruction of a plugin. If that happens during the destruction of a plugin a thread can reference the members that have been destructed already and so segfault. I can see it is a common problem when people use `ThreadRAII` thinking it does everything for them. `ThreadRAII` as a member variable is not guaranteed to destroy before other member variables. Suggesting to remove `ThreadRAII` to avoid problems like that.

**Comment by srikanth-vv** [comment]
It seems adding following code in `Warehouse::Deinitialize()`, seems fixed the segmentation fault issue.
```
            if (m_resetThread.get().joinable())
                m_resetThread.get().join();
```
Is it the correct solution?

**Comment by npoltorapavlo** [comment]
yes, please fix for Warehouse plugin in #3399

**Comment by npoltorapavlo** [comment]
@anand-ky ThreadRAII is still used in project. FYI segfaults will occur due to that

**Comment by npoltorapavlo** [comment]
@anand-ky AirplayService and other rdk services still use ThreadRAII . this is a source of segfaults
