### ISSUE TITLE
WebKitBrowser: How to detect that url was successfully loaded or failed to load?

### ISSUE THREAD

**Issue by marcin-mielczarczyk-red** [rdkcentral/rdkservices#4140]
I tried to implement the way to detect that selected URL has been successfully loaded or failed to load and have problem with that.
There are following callbacks available in the browser plugin (WebKitImplementation.cpp file):

- uriChangedCallback
- loadChangedCallback
- loadFailedCallback

*When a new domain URL load process is initiated, process seems to be straightforward:

url:  https://www.live.bbctvapps.co.uk

1) uriChangedCallback (url: https://www.live.bbctvapps.co.uk)
2) loadChangedCallback() is being called with following events: WEBKIT_LOAD_STARTED, WEBKIT_LOAD_COMMITTED, WEBKIT_LOAD_FINISHED

URL load detection: wait for loadChangedCallback() with WEBKIT_LOAD_FINISHED event

*When loading url from the same domain (boot url has been already loaded), the only callback which is being called is uriChangedCallback():

boot url: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot
app url: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Euronews

1) uriChangedCallback (url: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Euronews)

URL load detection: wait for uriChangedCallback() with metrological url

*When loading wrong url from a new domain:

url: https://not_valid_url.com

1) uriChangedCallback (url: https://not_valid_url.com)
2) loadChangedCallback (event: WEBKIT_LOAD_STARTED)
3) uriChangedCallback (url: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot)
4) loadFailedCallback (url: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot)

URL failed detection: loadFailedCallback() contains previous url, but also there is uriChangedCallback() with metrological url which breaks failure detection

Could you please describe what is the proper way to handle success or failed url load detection?

**Comment by modeveci** [comment]
The PR related LoadFailed with the proper URL has been merged in February, thus using that PR has resolved that part of question. The rest of question can be followed from here https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1106
Closing this issue.
